### ISSUE TITLE
Meeting Minutes - Milestone 3

### ISSUE THREAD

**Issue by ssyayayy** [UBC-MDS/DSCI_525_Group13_Rainfall#33]
Tues. Apr 20 - 2pm - 4pm PST(during lab)
- walked through Exercises 1 and 2 together as a group with one person screen sharing.
- confirmed all members have access to jupyterHub (TLJH in EC2 and AWS managed jupyterHub in cluster)

Next meeting 2pm PST on Friday, April 23 to complete the following together and submit. No prep required before meeting.
- Develop a ML model using scikit-learn
- Obtain best hyperparameter settings using spark's MLlib

**Comment by williamxu7** [comment]
We had a meeting today from 2:00 pm - 4:50 pm. We completed all the required tasks, and now we are going to release our milestone 3 and submit on Canvas.
