### ISSUE TITLE
3. Downloading the data

### ISSUE THREAD

**Issue by mikelynch416** [UBC-MDS/DSCI_525_Group13_Rainfall#4]
rubric={correctness:10}

Download the data from figshare to your local computer using the figshare API (you can make use of requests library).
Extract the zip file, again programmatically, similar to how we did it in class.
You can download the data and unzip it manually. But we learned about APIs, and so we can do it in a reproducible way with the requests library, similar to how we did it in class.

There are 5 files in the figshare repo. The one we want is: data.zip

**Comment by d-sel** [comment]
Confirmed all were able to use download code successfully.
