### ISSUE TITLE
Meeting minutes: week 1

### ISSUE THREAD

**Issue by mikelynch416** [UBC-MDS/DSCI_525_Group13_Rainfall#8]
- worked on team work contract: https://docs.google.com/document/d/1YiKpAI7SOByUEvVZuY6lgJZao44wGtaIJhtS_VNj0II/edit
- created repo: https://github.com/UBC-MDS/DSCI_525_Group13_Sirius-A

Assigned task for this week:
- [x] need to update readme: Selma
- [x] download the data (in notebook/milestone_1.ipynb): Selma
- [x] combining the CSVs (in notebook/milestone_1.ipynb): William
- [x] Load the combined CSV to memory and perform a simple EDA (Python): Mike
- [x] Load the combined CSV to memory and perform a simple EDA (R): Ivy
- [x] Discuss any challenges or difficulties (in reflection section of notebook): All

**Comment by d-sel** [comment]
From Fri. Apr 2 meeting (11am):
- to have milestone components complete by end of day Apr 2nd.
- all members to add usage stats to notebook
- team meeting Sat. Apr 3 at 2pm PST to walk-through overall milestone notebook for submission.
